name: conecta
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  multi_select_flutter: ^4.1.3


  # 🔥 Firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.6

  # 📦 Altres
  url_launcher: ^6.2.5
  # file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/logo3.png
    - assets/images/logo4.png
    - assets/images/logo5.png
    - assets/images/veure_totes_les_ofertes.png
    - assets/avatars/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  fullscreen: true
